### ISSUE TITLE
Investigate parsing and mapping of taxonomy and affiliation identifiers

### ISSUE THREAD

**Issue by marks** [untoldone/bloomapi#30]
Need per discussions with others and the following on the [docgraph](https://groups.google.com/forum/#!forum/docgraph) mailing list

> I was hoping someone already figured out a good way to separate out the dentist and nurses out of the NPPES data by Taxonomy Code in order to get a more manageable data set to hopefully get more insight on the doctor data.  
> via Ross Parks <parkselectricalservice@gmail.com>

**Comment by untoldone** [comment]
Taxonomy codes can now be queried at http://www.bloomapi.com/api/search/nucc.hcpt. Classifications of codes can be queried at http://www.bloomapi.com/api/search/nucc.hcpt_classifications.

I will be pushing out documentation for this with the next release.
