### ISSUE TITLE
Searching for providers by geocoded location

### ISSUE THREAD

**Issue by etagwerker** [untoldone/bloomapi#48]
Hello, 

I am interested in contributing code for this feature. I am working on a healthcare project, which needs to run queries like "give me all the doctors in a 10 mile radius of this address".

I see that the information to geocode the location is in the database. I would need to process the entries in the database to store _latitude_ & _longitude_ per address. 

I was wondering a few things:
1. Should I create a new project (eg. `bloomapi-geolocation`) and add my new code there? 
2. If not, should I just add a few tasks to add the necessary columns and populate it using a geocoding tool like https://npmjs.org/package/node-geocoder?

Let me know what you had in mind. 

Thanks!

**Comment by aegixx** [comment]
This would be huge for my project - but noticed the PR got shut down.  Any updates?  I'm not a GO developer, but willing to give it a go (pun intended) if push (another pun) comes to shove... ;)

**Comment by untoldone** [comment]
The pull no longer made sense since the language changed. That said, BloomAPI has been built to pull in many different arbitrary datasources and put them all together for the API.

If someone made a new datasources that was just something like a CSV of geo-coded NPI addresses, that could very easily be re-included. This wouldn't need to be written in Go. I'd be happy to help make it happen on the API side quickly once the data is there.

**Comment by etagwerker** [comment]
I would be interested in porting this code to Go, but I don't have much time these days. :(

**Comment by untoldone** [comment]
@etagwerker @aegixx Any chance you think it could just be a script that uploaded a CSV to somewhere public based on the NPI input file with the practice address + business address fields? I'd take care of the rest sometime soon if you found time for it!

**Comment by afs2015** [comment]
@untoldone, are you just looking to get all of the addresses in the NPI database but by the longitude/latitude into a CSV file?

**Comment by untoldone** [comment]
@afs2015 Yep -- if we just had a source of coded locations (that updates regularly with the latest NPI locations), I'd be able to easily pull that into the NPI + make it searchable.

**Comment by untoldone** [comment]
Likely won't get fixed anytime soon. At BloomAPI, we're now internally geocoding using Nominatim but don't currently publish that source anywhere. Feel free to reopen if anyone feels particularly strongly about this getting added.
