### ISSUE TITLE
500 on specific website NPIs

### ISSUE THREAD

**Issue by untoldone** [untoldone/bloomapi#65]
For example: /npis/1700097797 currently causes a 500 internal server errror.

**Comment by untoldone** [comment]
1306933650 does as well

**Comment by sergeyltd** [comment]
but API is working (http://www.bloomapi.com/api/npis/1700097797), looks like the result for this NPI(1700097797) does not have so many data as any other NPIs  and front UI expect some special data which not exist

**Comment by untoldone** [comment]
@sergeyltd Yeah -- the UI expects an address to exist which appears to be missing from the API for these NPIs.

The address should be present on both of these NPIs via the API but they seem to be missing. The UI could more gracefully handle missing information as well.

**Comment by untoldone** [comment]
This was fixed by a number of recent commits in BloomAPI/ NPI. Fixes will be in next release.
