### ISSUE TITLE
Error reading dissemination file when deploying BloomAPI

### ISSUE THREAD

**Issue by boroth** [untoldone/bloomapi#66]
I've gone through the installation/deployment instructions and everything seems to be setup so far, until I get to running `go run ./bloomnpi.go fetch`. It's spitting back an error that reads: "Error: read data/NPPES_Data_Dissemination_December_2014.zip: invalid argument"

I've been doing a bit of debugging on my own, and can tell you that the file has indeed been downloaded into that location, and it makes it through the `npiFile(r)` function in the helpers/nppesOpener.go file.  It seems to be failing when we call `file.Open()` after verifying that it's a zip file and an npiFile.

**Comment by boroth** [comment]
For debugging purposes, I've commented out the download portion of the fetch.go script in order to just test the opening of my existing dissemination zip file. I've downloaded it at least 4 times today, so I doubt the zip itself is corrupted or anything, but if you think that might be the case, I can re-download it again just to make sure

**Comment by untoldone** [comment]
Could you check the version of go are you running? Thanks!

**Comment by boroth** [comment]
go version go1.2.1 linux/amd64

**Comment by untoldone** [comment]
Ah, that sounds like the issue. There's a bug in go 1.2.1's zip processing
for large zip files (see https://code.google.com/p/go/issues/detail?id=7069
).

Running 1.3+ should fix the issue.

**Comment by boroth** [comment]
Awesome. I had used apt-get in order to get/install Go, so I guess that package hasn't been updated in a while :(

Running the fetch now, it's downloaded the zip file and it seems to be doing processing now. Depending on how proactive I'm feeling after lunch, I may go in and try to add some progress messages for the fetch processes. Since it takes so long, it'd be nice at least to know when the download has finished and processing has begun. Also, I forget sometimes when I start the process, so I can't remember how long it's actually been running for.

Thanks for the help!

**Comment by untoldone** [comment]
No problem at all -- let me know if you hit any other problems
