### ISSUE TITLE
Unable to search mychart locations

### ISSUE THREAD

**Issue by abrararies** [untoldone/bloomapi#74]
I keep trying to test out 
curl -XGET https://www.bloomapi.com/api/search/bloomapi.epic.mychart_locations?secret=<secret key>

with the developer secret key obtained after sign up but it gives an error telling me to contact support@bloomapi.com.

**Comment by untoldone** [comment]
The datasource isn't included in the open source project. If you are interested in getting access to that particular dataset, please email support@bloomapi.com

Thanks!

**Comment by abrararies** [comment]
Yes I sent an email to you.
I'm sorry, I realize now that you were away.

Thank you! :)
