### ISSUE TITLE
Broken link to documentation

### ISSUE THREAD

**Issue by jdavisp3** [untoldone/bloomapi#76]
The README links to the documentation and the contribution pages appear broken:

* http://www.bloomapi.com/documentation
* https://www.bloomapi.com/contribute

Is this package still supported?

**Comment by untoldone** [comment]
Yes, this is still supported and it still runs and is monitored 24/7 in hosted form, but it is not actively developed. You can find the documentation at https://www.bloomapi.com/documentation/public-data which includes instructions for getting BloomAPI running locally. As a heads up, its possible you could hit an issue or two building locally if any referenced libraries have broken over the last few months, but feel free to post an issue, email support@bloomapi.com, or use the chat on https://www.bloomapi.com if you'd like help in getting started.

I fixed the documentation links referenced in the readme with 61284eb3d9158d85db9884bc71205971ff084cb6

**Comment by jdavisp3** [comment]
Thanks very much!
